"""Schemas module initialization."""

from app.schemas.common import (
    PaginationParams,
    PaginatedResponse,
    SortParams,
    SearchParams,
    DateRangeParams,
    HealthCheck,
    ErrorResponse,
    SuccessResponse,
    BulkOperationResult,
)
from app.schemas.user import (
    UserCreate,
    UserUpdate,
    UserResponse,
    UserBrief,
    UserList,
    LoginRequest,
    TokenResponse,
    TokenRefreshRequest,
    PasswordChange,
)
from app.schemas.project import (
    ProjectCreate,
    ProjectUpdate,
    ProjectResponse,
    ProjectBrief,
    ProjectDetail,
    ProjectList,
    ProjectStats,
)
from app.schemas.test_case import (
    TestStep,
    TestCaseCreate,
    TestCaseUpdate,
    TestCaseResponse,
    TestCaseBrief,
    TestCaseDetail,
    TestCaseList,
    TestCaseFilter,
    TestCaseBulkUpdate,
)
from app.schemas.execution import (
    ExecutionCreate,
    ExecutionUpdate,
    ExecutionResponse,
    ExecutionBrief,
    ExecutionDetail,
    ExecutionList,
    ExecutionProgress,
    ExecutionSummary,
    TestResultCreate,
    TestResultResponse,
)

__all__ = [
    # Common
    "PaginationParams",
    "PaginatedResponse",
    "SortParams",
    "SearchParams",
    "DateRangeParams",
    "HealthCheck",
    "ErrorResponse",
    "SuccessResponse",
    "BulkOperationResult",
    # User
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserBrief",
    "UserList",
    "LoginRequest",
    "TokenResponse",
    "TokenRefreshRequest",
    "PasswordChange",
    # Project
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectBrief",
    "ProjectDetail",
    "ProjectList",
    "ProjectStats",
    # Test Case
    "TestStep",
    "TestCaseCreate",
    "TestCaseUpdate",
    "TestCaseResponse",
    "TestCaseBrief",
    "TestCaseDetail",
    "TestCaseList",
    "TestCaseFilter",
    "TestCaseBulkUpdate",
    # Execution
    "ExecutionCreate",
    "ExecutionUpdate",
    "ExecutionResponse",
    "ExecutionBrief",
    "ExecutionDetail",
    "ExecutionList",
    "ExecutionProgress",
    "ExecutionSummary",
    "TestResultCreate",
    "TestResultResponse",
]
